// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (todo)
VALUES ($1)
`

func (q *Queries) CreateTodo(ctx context.Context, todo string) error {
	_, err := q.db.Exec(ctx, createTodo, todo)
	return err
}

const getTodos = `-- name: GetTodos :many
SELECT todo FROM todos
`

func (q *Queries) GetTodos(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var todo string
		if err := rows.Scan(&todo); err != nil {
			return nil, err
		}
		items = append(items, todo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
